### ISSUE TITLE
websocket连接频繁报错

### ISSUE THREAD

**Issue by benx1n** [tencent-connect/botpy#111]
正常使用中出现，但不清楚具体复现条件
[ERROR] (gateway.py:50)on_error [botpy] websocket连接: <aiohttp.client_ws.ClientWebSocketResponse object at 0x00000177BA2EA4A0>, 异常信息 : 'NoneType' object has no attribute 'get'

Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\botpy\client.py", line 237, in bot_connect
    await client.ws_connect()
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\botpy\gateway.py", line 123, in ws_connect
    await self.on_message(ws_conn, msg.data)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\botpy\gateway.py", line 95, in on_message
    func(ctx, msg.get("d"))
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\botpy\connection.py", line 136, in parse_message_delete
    _message = Message(self.api, ctx, data)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\botpy\message.py", line 26, in __init__
    self.author = self._User(data.get("author"))
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\botpy\message.py", line 41, in __init__
    self.id = data.get("id")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by benx1n** [comment]
申请的是私域bot，同时仅订阅了guild_messages

**Comment by GLGDLY** [comment]
可以试试更新一下到目前github的版本，最近优化了这个默认值的问题

**Comment by benx1n** [comment]
更新了，等待后续复现
目前来看仅发生在提交bot上线审核后，测试环境中依旧无法复现
添加公域事件后，会在报错前打印一行
`_parser unknown event public_message_delete.`

**Comment by ReadSmall** [comment]
已解决
