### ISSUE TITLE
WebSocket重连失败无法继续使用

### ISSUE THREAD

**Issue by Bill-Haku** [tencent-connect/botpy#114]
长期使用中可能会遇到WebSocket关闭后重连失败的问题，导致程序无法继续提供服务。

log和报错结果如下：
```
[INFO] on_closed (gateway.py:54):[botpy] 关闭, 返回码: 4009, 返回信息: Session timed out
[INFO] multi_run (connection.py:59):[botpy] 最大并发连接数: 1, 启动会话数: 1
[INFO] bot_connect (client.py:234):[botpy] 会话启动中...
[INFO] ws_connect (gateway.py:110):[botpy] 启动中...
[ERROR] on_error (gateway.py:50):[botpy] websocket连接: None, 异常信息 : Cannot connect to host api.sgroup.qq.com:443 ssl:default [nodename nor servname provided, or not known]
Traceback (most recent call last):
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/botpy/client.py", line 238, in bot_connect
    await client.ws_connect()
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/botpy/gateway.py", line 117, in ws_connect
    async with session.ws_connect(self._session["url"]) as ws_conn:
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.sgroup.qq.com:443 ssl:default [nodename nor servname provided, or not known]
```

**Comment by ReadSmall** [comment]
尝试克隆目前最新版的源码看下是否能够解决
