### ISSUE TITLE
self.api.post_message 仅仅发送本地图片失败

### ISSUE THREAD

**Issue by Hatsunespica** [tencent-connect/botpy#118]
示例调用：

```
    async def on_message_create(self, message: Message):
        await self.api.post_message(channel_id=message.channel_id, file_image="resource/test.png")
```

错误信息
```
[ERROR] (http.py:35)_handle_response    [botpy] 接口请求异常，, 错误代码: 500, 返回内容: {'code': 40011, 'message': 'dns resolve'}, trace_id:e127e4746b17b578e9f1a9d8cf0fc79b
Traceback (most recent call last):
  File "D:\software\Anaconda3\lib\site-packages\botpy\client.py", line 277, in _run_event
    await coro(*args, **kwargs)
  File "at_reply.py", line 33, in on_message_create
    await self.api.post_message(channel_id=message.channel_id, file_image="resource/test.png")
  File "D:\software\Anaconda3\lib\site-packages\botpy\api.py", line 508, in post_message
    return await self._http.request(route, json=payload)
  File "D:\software\Anaconda3\lib\site-packages\botpy\http.py", line 135, in request
    return await _handle_response(response)
  File "D:\software\Anaconda3\lib\site-packages\botpy\http.py", line 45, in _handle_response
    raise error_dict_get(msg=message)
botpy.errors.ServerError: dns resolve
```

假如我模仿`message.reply`的实现在`self.api.post_message` 的调用参数里加上`msg_id=message.id`，此时就正常发送了。请问发送本地图片必须加上msg_id是必要的吗0 0?

**Comment by ReadSmall** [comment]
主动消息暂时不支持发送本地图片哈, 等梳理完消息链路之后会通知的.

**Comment by Hatsunespica** [comment]
感谢回复！
