### ISSUE TITLE
push channel message not allow

### ISSUE THREAD

**Issue by b3601993** [tencent-connect/botpy#132]
[ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/371818661/messages, 错误代码: 500, 返回内容: {'code': 304046, 'message': 'push channel message not allow'}, trace_id:54f641d210b7e954703564e7530be5d7
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/botpy/client.py", line 279, in _run_event
    await coro(*args, **kwargs)
  File "/Users/yutao/vscodeproject/qqbotpy/announce.py", line 21, in on_at_message_create
    await self.api.post_message(message.channel_id, content="command received: %s" % message.content)
  File "/usr/local/lib/python3.11/site-packages/botpy/api.py", line 508, in post_message
    return await self._http.request(route, json=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botpy/http.py", line 186, in request
    return await _handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botpy/http.py", line 83, in _handle_response
    raise error_dict_get(msg=message) from None
botpy.errors.ServerError: push channel message not allow

之前都可以创建公告，多测试几次后，居然直接报错了~，公告创建然后删除，重复这种操作不可以吗？难道还有次数限制？开发代码肯定要来来回回测试的呀！

**Comment by b3601993** [comment]
[ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/9099812619143246624/announces, 错误代码: 500, 返回内容: {'code': 501006, 'message': 'create guild announces error'}, trace_id:b641543e6bdc0961e17ba5b800895daa
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/botpy/client.py", line 279, in _run_event
    await coro(*args, **kwargs)
  File "/Users/yutao/vscodeproject/qqbotpy/botai.py", line 15, in on_at_message_create
    await self.api.create_announce(message.guild_id, message.channel_id, message_id)
  File "/usr/local/lib/python3.11/site-packages/botpy/api.py", line 848, in create_announce
    return await self._http.request(route, json=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botpy/http.py", line 186, in request
    return await _handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botpy/http.py", line 83, in _handle_response
    raise error_dict_get(msg=message) from None
botpy.errors.ServerError: create guild announces error

**Comment by b3601993** [comment]
我知道原因了，因为在私域领域创建公告，是不被允许的，所以就报错了。这种错误建议优化下
