### ISSUE TITLE
botpy.errors.ServerError: no permission to use this keyboard template

### ISSUE THREAD

**Issue by b3601993** [tencent-connect/botpy#133]
**用的官方例子：demo_at_reply_keyboard.py**

<font color=red>没有任何改动，执行就报如下错误：（频道非私域频道）：</font>

[ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/344208314/messages, 错误代码: 500, 返回内容: {'code': 304037, 'message': 'no permission to use this keyboard template'}, trace_id:a5aec73999d90b58394b84185600b842
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/botpy/client.py", line 279, in _run_event
    await coro(*args, **kwargs)
  File "/Users/yutao/vscodeproject/qqbotpy/demo_at_reply_keyboard.py", line 17, in on_at_message_create
    await send_template_keyboard(self.api, message)
  File "/Users/yutao/vscodeproject/qqbotpy/demo_at_reply_keyboard.py", line 24, in send_template_keyboard
    await api.post_keyboard_message(message.channel_id, markdown=markdown, keyboard=keyboard)
  File "/usr/local/lib/python3.11/site-packages/botpy/api.py", line 559, in post_keyboard_message
    return await self._http.request(route, json=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botpy/http.py", line 186, in request
    return await _handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botpy/http.py", line 83, in _handle_response
    raise error_dict_get(msg=message) from None
botpy.errors.ServerError: no permission to use this keyboard template

我的机器人有管理员权限的。所以不是很明白，为啥会报这种错误！！！

**Comment by traveler-vee** [comment]
这里建议直接反馈到QQ机器人开发者频道中，有专门的同学跟进接口问题。这里主要反馈sdk相关的问题

**Comment by b3601993** [comment]
> 这里建议直接反馈到QQ机器人开发者频道中，有专门的同学跟进接口问题。这里主要反馈sdk相关的问题

搞技术的，还要去群里反馈问题，这不合适吧，你们可以创建一个空项目，专门用来处理issue问题的。

**Comment by SaucePlum** [comment]
没有markdown模板按钮权限

**Comment by traveler-vee** [comment]
建议申请权限再试下
