### ISSUE TITLE
bot好像支持本地上传图片了

### ISSUE THREAD

**Issue by Suz1e** [tencent-connect/botpy#198]
看大佬有说可以转base64上传本地图片，但是我试了一下失败了，但又有人成功了（不知道他是不是pythonSDK）
也有可能是PythonSDK还未更新？
@SaucePlum

**Comment by SlieFamily** [comment]
你好，我已经提交了 pr 实现了此功能。（见 #199）https://github.com/tencent-connect/botpy/pull/199

**Comment by Suz1e** [comment]
> 你好，我已经提交了 pr 实现了此功能。（见 #199 ）

我看到了，是这样的方法

**Comment by ncy0201** [comment]
大佬们成功了吗，我一直报错，求指导

报错信息：

```
接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/76824BF877D9B93EB67EF4A465703971/files, 错误代码: 400, 返回内容: {'message': '富媒体文件格式不支持', 'code': 850019, 'err_code': 40034002, 'trace_id': '9af3e5f220dd5015b989a8b053413e07'}, trace_id:9af3e5f220dd5015b989a8b053413e07
Traceback (most recent call last):
  File "D:\NiuChangyu\Anaconda\envs\qq\lib\site-packages\botpy\client.py", line 285, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\NiuChangyu\Desktop\qqbot\qqgroupbot.py", line 268, in on_group_at_message_create
    uploadMedia = await message._api.post_group_base64file(
  File "D:\NiuChangyu\Anaconda\envs\qq\lib\site-packages\botpy\api.py", line 1532, in post_group_base64file 
    return await self._http.request(route, json=payload)
  File "D:\NiuChangyu\Anaconda\envs\qq\lib\site-packages\botpy\http.py", line 190, in request
    return await _handle_response(response)
  File "D:\NiuChangyu\Anaconda\envs\qq\lib\site-packages\botpy\http.py", line 85, in _handle_response       
    raise ServerError(message) from None  # adding from None to prevent chain exception being raised        
botpy.errors.ServerError: 富媒体文件格式不支持
```

代码：
```
async def on_group_at_message_create(self, message: GroupMessage):
    file_path = 'img/1.png'
    with open(file_path, "rb") as img_file:
        img_bytes = img_file.read()
    base64_encoded_data = base64.b64encode(img_bytes).decode('utf-8')
    uploadMedia = await message._api.post_group_base64file(
        group_openid=message.group_openid, 
        file_type=1, # 文件类型要对应上，具体支持的类型见方法说明
        file_data=base64_encoded_data # 传递 base64 编码后的字符串
    )
  
    await message._api.post_group_message(
          group_openid=message.group_openid,
          msg_type=7,  # 7表示富媒体类型
          msg_id=message.id, 
          media=uploadMedia
    )
```

其中

```
async def post_group_base64file(
    self,
    group_openid: str,
    file_type: int,
    file_data: str,
    srv_send_msg: bool = False,
) -> message.Media:
    """
    上传/发送群聊图片
    Args:
      group_openid (str): 您要将消息发送到的群的 ID
      file_type (int): 媒体类型：1 图片png/jpg，2 视频mp4，3 语音silk，4 文件（暂不开放）
      file_data (str): 二进制文件的base64编码，可用于代替网络url资源，实现本地上传文件
      srv_send_msg (bool): 设置 true 会直接发送消息到目标端，且会占用主动消息频次
    """
    payload = locals()
    payload.pop("self", None)
    route = Route("POST", "/v2/groups/{group_openid}/files", group_openid=group_openid)
    return await self._http.request(route, json=payload)
```
